# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('submition_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0648\u0642\u062a \u0627\u0644\u0627\u0636\u0627\u0641\u0629')),
            ],
        ),
        migrations.CreateModel(
            name='Question_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question_session'),
        ),
    ]
