# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_session',
            new_name='Question_sessions',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='submition_date',
            new_name='submission_date',
        ),
    ]
